[package]
name = "HL2-Speed"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3", features = ["minwindef", "memoryapi", "winuser", "winbase", "synchapi"] }